version: "3.0"
services:
  myepitechnotif:
    container_name: myepitechnotif
    image: alwyn974/myepitechnotif:latest
    restart: always
    environment:
      - HOST=127.0.0.1
      - PORT=8080
      - NO_WINDOW=0
      - BROWSER_ARGS=--no-sandbox
    volumes:
      - ./cookies.json:/MyEpitechNotif/cookies.json